scrub_list = [
                           " ex",
                           "Mega ",
                           "M ",
                           "-GX",
                           "Teal Mask",
                           "Wellspring Mask",
                           "Hearthflame Mask",
                           "Cornerstone Mask",
                           "-EX",
                           " BREAK",
                           " VMAX",
                           " VSTAR",
                           " V-UNION",
                           " LV.X",
                           "LEGEND",
                           "Primal ",
                           "Prism Star",
                           "Origin Forme ",
                           "Paldean ",
                           "Hisuian ",
                           "Galarian ",
                           "Alolan ",
                           "Dusk Mane ",
                           "Dawn Wings ",
                           "Detective",
                           "White ",
                           "Black ",
                           "Fan ",
                           "Wash ",
                           "Mow ",
                           "Heat ",
                           "Frost ",
                           "Erika’s ",
                           "Blaine’s ",
                           "Brock’s ",
                           "Lt. Surge’s ",
                           "Misty’s ",
                           "Sabrina’s ",
                           "N’s ",
                           "Lillie’s ",
                           "Iono’s ",
                           "Larry’s ",
                           "Marnie’s ",
                           "Cynthia’s ",
                           "Team Rocket’s ",
                           "Steven’s ",
                           "Hop’s ",
                           "Ethan’s ",
                           "Arven’s ",
                           "Ash’s ",
                           "Ash-",
                           "Imakuni?’s ",
                           "Team Magma’s ",
                           "Team Aqua’s ",
                           "Holon’s ",
                           "Rocket’s ",
                           "Koga’s ",
                           "Giovanni’s ",
                           "Dark ",
                           "Flying ",
                           "Surfing",
                           "Shining ",
                           " E4",
                           " GL",
                           " Normal Forme",
                           " Attack Forme",
                           " Defense Forme",
                           " Speed Forme",
                           " Rain Form",
                           " Snow-Cloud Form",
                           "Sunny Form"
                           ]

card_filters_tcg_model = {
                          
                "Card-Type": ["Pokemon", "Trainer", "Supporter", "Item", "Energy", 
                              "Basic Energy", "Tool", "Stadium", "Special Energy", "Technical Machine",
                              "Rocket's Secret Machine", "Tool F", "Goldenrod Game Corner"],

                "Type": ["Grass", "Fire", "Water", "Lightning", "Psychic", 
                         "Fighting", "Darkness", "Metal", "Fairy", "Dragon", 
                         "Colorless"],

                "Stage": ["Basic", "Stage 1", "Stage 2", "VMAX", "VSTAR", 
                          "Mega", "Level-Up", "BREAK", "V-UNION", "Baby", 
                          "LEGEND", "Restored"],

                
                "Rarity": ["ACE SPEC Rare", "Amazing Rare", "Black White Rare", "Common", "Double Rare",
                        "Holo Rare V", "Holo Rare VMAX", "Holo Rare VSTAR", "Hyper Rare", "Illustration Rare",
                        "LEGEND", "Mega Attack Rare", "Mega Hyper Rare", "Promo", "Radiant Rare",
                        "Rainbow Rare", "Rare", "Rare BREAK", "Rare Holo", "Rare Holo EX",
                        "Rare Holo GX", "Rare Holo LV.X", "Rare Holo Star", "Rare Holo ex", "Rare Prime",
                        "Rare Prism Star", "Rare Secret", "Rare Shining", "Rare Shiny GX", "Shiny Rare",
                        "Shiny Rare V or VMAX", "Shiny Ultra Rare", "Special Full Art", "Special Illustration Rare", "Trainer Gallery Holo Rare",
                        "Trainer Gallery Holo Rare V", "Trainer Gallery Holo Rare V or VMAX", "Trainer Gallery Secret Rare", "Trainer Gallery Ultra Rare", "Ultra Rare",
                        "Uncommon"]
                }

card_filters_pocket_model = {
                             
            "Card-Type": ["Pokemon", "Supporter", "Item", "Tool", "Stadium"],

            "Type": ["Grass", "Fire", "Water", "Lightning", "Psychic", 
                    "Fighting", "Darkness", "Metal", "Dragon", 
                    "Colorless"],

            "Stage": ["Basic", "Stage 1", "Stage 2"],
            
            "Rarity": ["1 Diamond", "2 Diamond", "4 Diamond", "3 Diamond", "1 Star",
                        "2 Star", "3 Star", "1 Shiny", "2 Shiny", "Crown"]
        }