scrub_list = [
                           " ex",
                           "Mega ",
                           "M ",
                           "-GX",
                           "Teal Mask",
                           "Wellspring Mask",
                           "Hearthflame Mask",
                           "Cornerstone Mask",
                           "-EX",
                           " BREAK",
                           " VMAX",
                           " VSTAR",
                           " V-UNION",
                           " LV.X",
                           "LEGEND",
                           "Primal ",
                           "Prism Star",
                           "Origin Forme ",
                           "Paldean ",
                           "Hisuian ",
                           "Galarian ",
                           "Alolan ",
                           "Dusk Mane ",
                           "Dawn Wings ",
                           "Detective",
                           "White ",
                           "Black ",
                           "Fan ",
                           "Wash ",
                           "Mow ",
                           "Heat ",
                           "Frost ",
                           "Erika’s ",
                           "Blaine’s ",
                           "Brock’s ",
                           "Lt. Surge’s ",
                           "Misty’s ",
                           "Sabrina’s ",
                           "N’s ",
                           "Lillie’s ",
                           "Iono’s ",
                           "Larry’s ",
                           "Marnie’s ",
                           "Cynthia’s ",
                           "Team Rocket’s ",
                           "Steven’s ",
                           "Hop’s ",
                           "Ethan’s ",
                           "Arven’s ",
                           "Ash’s ",
                           "Ash-",
                           "Imakuni?’s ",
                           "Team Magma’s ",
                           "Team Aqua’s ",
                           "Holon’s ",
                           "Rocket’s ",
                           "Koga’s ",
                           "Giovanni’s ",
                           "Dark ",
                           "Flying ",
                           "Surfing",
                           "Shining ",
                           " E4",
                           " GL",
                           " Normal Forme",
                           " Attack Forme",
                           " Defense Forme",
                           " Speed Forme",
                           " Rain Form",
                           " Snow-Cloud Form",
                           "Sunny Form"
                           ]